version: '3.8'
services:
  stats-server:
    build: ./ewm-stat-service/stat_server
    image: stat_server:latest
    container_name: stat_server
    ports:
      - "9090:9090"
    depends_on:
      - stats_service-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats_service-db:5432/stat_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=your_stats_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app-network

  stats_service-db:
    image: postgres:16.1
    container_name: stats_service-db
    ports:
      - "6666:5432"
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_stats_password
    networks:
      - app-network

  ewm-service:
    build: ./ewm-main-service
    image: ewm-service:latest
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=your_ewm_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - STATS_SERVICE_URL=http://stats-server:8080
    networks:
      - app-network

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6464:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_ewm_password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge