services:
  stats-server:
    build: ./ewm-stat-service/stat_server
    image: stats-service
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - statdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statdb:5432/statdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JAVA_OPTS=-Djdk.httpclient.HttpClient.log=errors,requests

  statdb:
    image: postgres:16.1
    volumes:
      - /var/lib/postgresql/data/
    container_name: statdb

    environment:
      - POSTGRES_DB=statdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ./ewm-main-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewmdb
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewmdb:5432/ewmdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - STAT_SERVER_URL=http://stats-server:9090
    #   - JAVA_OPTS=-Djdk.httpclient.HttpClient.log=errors,requests

  ewmdb:
    image: postgres:16.1
    volumes:
      - /var/lib/postgresql/data/
    container_name: ewmdb
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres